[build]
cmd = "npm ci --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npx serve -s dist -p $PORT"
healthcheckPath = "/"

[env]
NODE_VERSION = "20"
VITE_API_URL = "/api/v1"
VITE_ENABLE_LOGIN = "true"
VITE_SUPABASE_URL = "https://fqwdbywgknavgwqpnlkj.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxd2RieXdna25hdmd3cXBubGtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNzc2MDQsImV4cCI6MjA2Njc1MzYwNH0._CJ-IvMB1JqotdMQla75qj8U8SFZkEsEi2YWJSeHpMM"
VITE_DEMO_MODE = "false"