# Google Cloud Build設定
steps:
  # バックエンドDockerイメージビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/salon-backend:$COMMIT_SHA'
      - '-f'
      - 'backend/Dockerfile.gcp'
      - 'backend/'
    id: 'build-backend'

  # イメージをContainer Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/salon-backend:$COMMIT_SHA'
    id: 'push-backend'

  # データベースマイグレーション実行
  - name: 'gcr.io/$PROJECT_ID/salon-backend:$COMMIT_SHA'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export DATABASE_URL=$$DATABASE_URL
        npm run db:push
    secretEnv: ['DATABASE_URL']
    id: 'migrate-db'

  # Cloud Runにデプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'salon-backend'
      - '--image=gcr.io/$PROJECT_ID/salon-backend:$COMMIT_SHA'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--port=8080'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--min-instances=1'
      - '--max-instances=100'
      - '--allow-unauthenticated'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-cloudsql-instances=$PROJECT_ID:asia-northeast1:salon-db'
    id: 'deploy-backend'

  # フロントエンドビルド
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        npm ci
        npm run build
        gsutil -m rsync -r -d dist gs://$PROJECT_ID-salon-frontend
    id: 'deploy-frontend'

# 環境変数（Cloud Secret Manager使用）
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/database-url/versions/latest
      env: 'DATABASE_URL'

# ビルド設定
options:
  machineType: 'E2_HIGHCPU_8'
  
# タイムアウト
timeout: '1200s'