# 🚨 美容室統合管理システム - アラート設定

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@salon-system.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'salon-team'

receivers:
  - name: 'salon-team'
    email_configs:
      - to: 'admin@salon-system.com'
        subject: '🚨 美容室システムアラート: {{ .GroupLabels.alertname }}'
        body: |
          美容室統合管理システムでアラートが発生しました。

          📊 アラート詳細:
          {{ range .Alerts }}
          - アラート名: {{ .Annotations.summary }}
          - 詳細: {{ .Annotations.description }}
          - 発生時刻: {{ .StartsAt }}
          {{ end }}

          システムの確認をお願いします。

    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#salon-alerts'
        title: '🚨 美容室システムアラート'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']