global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'salon-app'
    static_configs:
      - targets: ['salon-backend:4002']
    metrics_path: '/health/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'salon-app-health'
    static_configs:
      - targets: ['salon-backend:4002']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 60s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s